name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            cmake-opts: 
          - os: windows-2019
            cmake-opts: -A x64
          - os: macos-10.15
            cmake-opts:
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: sudo apt-get update -y && sudo apt-get install -yq xorg-dev libgtk-3-dev libasound2-dev

      - name: Configure
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
          cmake -S $GITHUB_WORKSPACE -B build/ -DCMAKE_BUILD_TYPE=Release ${{matrix.cmake-opts}}

      - name: Build
        working-directory: ${{runner.workspace}}
        shell: bash
        run: cmake --build build/ --config Release





